DROP TABLE IF EXISTS log;
CREATE TABLE log (x UInt8) ENGINE = StripeLog;
SELECT * FROM log ORDER BY x;
INSERT INTO log VALUES (0);
INSERT INTO log VALUES (1);
INSERT INTO log VALUES (2);
DROP TABLE log;
CREATE TABLE log (x UInt8) ENGINE = TinyLog;
CREATE TABLE log (x UInt8) ENGINE = Log;
