set allow_deprecated_syntax_for_merge_tree=1;
CREATE TABLE pk (d Date DEFAULT '2000-01-01', x UInt64, y UInt64, z UInt64) ENGINE = MergeTree(d, (x, y, z), 1);
SET min_insert_block_size_rows = 0, min_insert_block_size_bytes = 0;
SET max_block_size = 1;
-- Prevent remote replicas from skipping index analysis in Parallel Replicas. Otherwise, they may return full ranges and trigger max_rows_to_read validation failures.
SET parallel_replicas_index_analysis_only_on_coordinator = 0;
SET max_rows_to_read = 4;
SELECT * FROM pk WHERE x = 2 AND y = 11 ORDER BY ALL;
SET max_rows_to_read = 5;
SELECT * FROM pk WHERE x = 1 ORDER BY ALL;
SET max_rows_to_read = 9;
SELECT * FROM pk WHERE x = 3 ORDER BY ALL;
SET max_rows_to_read = 3;
SELECT * FROM pk WHERE x = 3 AND y = 44 ORDER BY ALL;
SET max_rows_to_read = 2;
SELECT * FROM pk WHERE x = 3 AND y = 44 AND z = 4935 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 44 AND z = 4578 ORDER BY ALL;
SET max_rows_to_read = 1;
SELECT * FROM pk WHERE x = 3 AND y = 44 AND z = 4934 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 44 AND z = 4936 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 44 AND z = 4577 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 44 AND z = 4579 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z > 5786 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z >= 5786 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z > 1235 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z >= 1235 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z >= 1000 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z >= 1000 AND x < 10000 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y >= 50 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y > 44 ORDER BY ALL;
SELECT * FROM pk WHERE x >= 3 AND y > 44 ORDER BY ALL;
SELECT * FROM pk WHERE x > 2 AND y > 44 ORDER BY ALL;
SELECT * FROM pk WHERE x = 3 AND y = 55 AND z = 5786 ORDER BY ALL;
SET max_rows_to_read = 15;
SET merge_tree_min_rows_for_seek = 0;
SELECT * FROM pk WHERE z = 2791 ORDER BY ALL;
SELECT * FROM pk WHERE z = 5786 ORDER BY ALL;
SELECT * FROM pk WHERE z = 1235 ORDER BY ALL;
SELECT * FROM pk WHERE z = 4578 ORDER BY ALL;
SET max_rows_to_read = 10;
SELECT * FROM pk WHERE y = 11 ORDER BY ALL;
SELECT * FROM pk WHERE y = 22 ORDER BY ALL;
SELECT * FROM pk WHERE y = 33 ORDER BY ALL;
SELECT * FROM pk WHERE y = 44 ORDER BY ALL;
SELECT * FROM pk WHERE y = 55 ORDER BY ALL;
