select arrayConcat(emptyArrayUInt8());
select arrayConcat(emptyArrayUInt8(), emptyArrayUInt8());
select arrayConcat(emptyArrayUInt8(), emptyArrayUInt8(), emptyArrayUInt8());
select arrayConcat([Null], emptyArrayUInt8(), [1]);
select arrayConcat([1, 2], [-1, -2], [0.3, 0.7], [Null]);
select arrayConcat(Null, emptyArrayUInt8());
select arrayConcat([1], [-1], Null);
select arrayConcat([1, 2], [3, 4]);
select arrayConcat([1], [2, 3, 4]);
SELECT arrayConcat(['abc'], ['def', 'gh', 'qwe']);
SELECT arrayConcat([1, NULL, 2], [3, NULL, 4]);
select arrayConcat([1, Null, 2], [3, 4]);
select arraySlice(Null, 1, 2);
select arraySlice([1, 2, 3, 4, 5, 6], Null, Null);
select arraySlice([1, 2, 3, 4, 5, 6], 2, Null);
select arraySlice([1, 2, 3, 4, 5, 6], Null, 4);
select arraySlice([1, 2, 3, 4, 5, 6], Null, -2);
select arraySlice([1, 2, 3, 4, 5, 6], -3, Null);
select arraySlice([1, 2, 3, 4, 5, 6], 2, 3);
select arraySlice([1, 2, Null, 4, 5, 6], 2, 4);
select arraySlice(['a', 'b', 'c', 'd', 'e'], 2, 3);
select arraySlice([Null, 'b', Null, 'd', 'e'], 2, 3);
select arraySlice([], materialize(NULL), NULL), 1 from numbers(2);
select arrayPushBack(Null, 1);
select arrayPushBack([1], 1);
select arrayPushBack([Null], 1);
select arrayPushBack([0.5, 0.7], 1);
select arrayPushBack([1], -1);
select arrayPushBack(['a', 'b'], 'cd');
select arrayPushBack(emptyArrayUInt8(), 1);
select arrayPushBack(emptyArrayUInt8(), -1);
select arrayPushFront(Null, 1);
select arrayPushFront([1], 1);
select arrayPushFront([Null], 1);
select arrayPushFront([0.5, 0.7], 1);
select arrayPushFront([1], -1);
select arrayPushFront(['a', 'b'], 'cd');
select arrayPushFront(emptyArrayUInt8(), 1);
select arrayPushFront(emptyArrayUInt8(), -1);
select arrayPopBack(Null);
select arrayPopBack(emptyArrayUInt8());
select arrayPopBack([1]);
select arrayPopBack([1, 2, 3]);
select arrayPopBack([0.1, 0.2, 0.3]);
select arrayPopBack(['a', 'b', 'c']);
select arrayPopFront(Null);
select arrayPopFront(emptyArrayUInt8());
select arrayPopFront([1]);
select arrayPopFront([1, 2, 3]);
select arrayPopFront([0.1, 0.2, 0.3]);
select arrayPopFront(['a', 'b', 'c']);
select * from array_functions;
select arrayConcat(arr1, arr2), arr1, arr2 from array_functions;
select arrayConcat(arr1, arr2, arr1), arr1, arr2 from array_functions;
select arr1, o, l, arraySlice(arr1, o, l) from array_functions;
select arr1, 2, 4, arraySlice(arr1, -4, -1) from array_functions;
select arr1, arrayPushFront(arr1, 1) from array_functions;
select arr1, arrayPushFront(arr1, 0.1) from array_functions;
select arr1, arrayPushFront(arr1, l) from array_functions;
select arr1, arrayPushFront(arr1, nl) from array_functions;
select arrayPushFront([1, 2, 3], l) from array_functions;
select 'arrayPushFront([1, 2, 3], nl)' from array_functions;
select arrayPushFront([1, 2, 3], nl) from array_functions;
select arr1, arrayPushBack(arr1, 1) from array_functions;
select arr1, arrayPushBack(arr1, 0.1) from array_functions;
select arr1, arrayPushBack(arr1, l) from array_functions;
select arr1, arrayPushBack(arr1, nl) from array_functions;
select arrayPushBack([1, 2, 3], l) from array_functions;
select arrayPushBack([1, 2, 3], nl) from array_functions;
select arr1, arrayPopFront(arr1) from array_functions;
select arr1, arrayPopBack(arr1) from array_functions;
select arr1, arrayPushFront(arr1, '1') from array_functions;
select arrayPushFront(['a', 'b', 'c'], val) from array_functions;
select arr1, arrayPushBack(arr1, '1') from array_functions;
select arrayPushBack(['a', 'b', 'c'], val) from array_functions;
