SELECT *
FROM mv_00508
ORDER BY x ASC;

SELECT *
FROM dst
ORDER BY x ASC;

SELECT *
FROM {CLICKHOUSE_DATABASE:Identifier}.mv_00508
ORDER BY x ASC;

SELECT *
FROM {CLICKHOUSE_DATABASE:Identifier}.dst
ORDER BY x ASC;