SELECT * FROM compression_codec ORDER BY id;
SELECT count(*) FROM compression_codec WHERE id = 2 GROUP BY id;
SELECT * FROM compression_codec_multiple ORDER BY id;
SELECT count(*) FROM compression_codec_multiple;
SELECT count(distinct data) FROM compression_codec_multiple;
SELECT floor(sum(somenum), 1) FROM compression_codec_multiple;
SELECT sum(cityHash64(*)) FROM compression_codec_multiple;
SELECT * FROM compression_codec_multiple_more_types order by id;
SELECT data FROM compression_codec_multiple_with_key WHERE id BETWEEN 3 AND 1112;
SELECT COUNT(DISTINCT data) FROM compression_codec_multiple_with_key WHERE id < 222;
SELECT data FROM compression_codec_multiple_with_key WHERE id = 2222;
