SYSTEM DROP  TABLE IF EXISTS test1;

SYSTEM DROP  TABLE IF EXISTS test2;

SYSTEM DROP  TABLE IF EXISTS mat_view;

CREATE TABLE test1
(
    a LowCardinality(String)
)
ENGINE = MergeTree()
ORDER BY a;

CREATE TABLE test2
(
    a UInt64
)
ENGINE = MergeTree()
ORDER BY a;

CREATE MATERIALIZED VIEW test_mv
TO test2
AS
SELECT toUInt64(a = 'test') AS a
FROM test1;

SYSTEM DROP  TABLE test_mv;

SYSTEM DROP  TABLE test1;

SYSTEM DROP  TABLE test2;