SELECT *
FROM `fill`
ORDER BY
    date ASC,
    val ASC;

SELECT *
FROM `fill`
ORDER BY
    date ASC,
    val ASC;

SELECT *
FROM `fill`
ORDER BY
    date ASC WITH FILL FROM toDate('2019-05-01') TO toDate('2019-05-31'),
    val ASC;

SELECT *
FROM `fill`
ORDER BY
    date DESC,
    val ASC WITH FILL FROM 1 TO 6;

SELECT *
FROM `fill`
ORDER BY
    date DESC WITH FILL TO toDate('2019-05-01') STEP -2,
    val DESC WITH FILL FROM 10 TO -5 STEP -3;

SELECT *
FROM `fill`
ORDER BY
    date ASC WITH FILL TO toDate('2019-06-23') STEP 3,
    val ASC WITH FILL FROM -10 STEP 2;

SELECT *
FROM `fill`
ORDER BY
    a ASC,
    b ASC;

SELECT *
FROM `fill`
ORDER BY
    a ASC,
    b ASC;

SELECT *
FROM `fill`
ORDER BY
    a ASC,
    b ASC WITH FILL TO 6 STEP 2;

SELECT *
FROM `fill`
ORDER BY a ASC WITH FILL STEP -1;

SELECT *
FROM `fill`
ORDER BY a ASC WITH FILL FROM 10 TO 1;

SELECT *
FROM `fill`
ORDER BY a DESC WITH FILL FROM 1 TO 10;

SELECT *
FROM `fill`
ORDER BY a ASC WITH FILL FROM -10 TO 10;