CREATE TABLE l (a String, b Tuple(String, String)) ENGINE = MergeTree ORDER BY tuple();
CREATE TABLE r (a String, c Tuple(String, String)) ENGINE = MergeTree ORDER BY tuple();
SET join_use_nulls = 0;
SELECT * from l LEFT JOIN r USING a ORDER BY a;
SELECT a from l RIGHT JOIN r USING a ORDER BY a;
SELECT * from l RIGHT JOIN r USING a ORDER BY a;
SET join_use_nulls = 1;
SELECT a from l LEFT JOIN r USING a ORDER BY a;
CREATE TABLE l (a String, b String) ENGINE = MergeTree ORDER BY tuple();
CREATE TABLE r (a String, c Array(String)) ENGINE = MergeTree ORDER BY tuple();
