CREATE TABLE rename_table_multiple (key Int32, value1 String, value2 Int32) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_bytes_for_wide_part=0;
INSERT INTO rename_table_multiple VALUES (1, 2, 3);
SELECT * FROM rename_table_multiple FORMAT TSVWithNames;
INSERT INTO rename_table_multiple VALUES (4, '5', 6);
SELECT * FROM rename_table_multiple ORDER BY key FORMAT TSVWithNames;
INSERT INTO rename_table_multiple VALUES (7, '8', 9, 10);
CREATE TABLE rename_table_multiple_compact (key Int32, value1 String, value2 Int32) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_rows_for_wide_part = 100000;
INSERT INTO rename_table_multiple_compact VALUES (1, 2, 3);
SELECT * FROM rename_table_multiple_compact FORMAT TSVWithNames;
INSERT INTO rename_table_multiple_compact VALUES (4, '5', 6);
SELECT * FROM rename_table_multiple_compact ORDER BY key FORMAT TSVWithNames;
INSERT INTO rename_table_multiple_compact VALUES (7, '8', 9, 10);
