CREATE TABLE t (x UInt8) ENGINE = TinyLog;
INSERT INTO t VALUES (1), (2), (3);
INSERT INTO t SELECT * FROM t;
SELECT count() FROM t;
CREATE TABLE t (x UInt8) ENGINE = Log;
CREATE TABLE t (x UInt8) ENGINE = StripeLog;
