SELECT count()
FROM testNullableStates;

SELECT count()
FROM testNullableStatesAgg;

SELECT ' ---- select without states ---- ';

SELECT
    id,
    count(),
    min(string),
    max(string),
    round(min(float64), 5),
    round(max(float64), 5),
    round(avg(float64), 5),
    round(sum(float64), 5),
    round(min(float32), 5),
    round(max(float32), 5),
    round(avg(float32), 5),
    round(sum(float32), 5),
    min(decimal325),
    max(decimal325),
    round(avg(decimal325), 5),
    sum(decimal325),
    min(date),
    max(date),
    min(datetime),
    max(datetime),
    min(datetime64),
    max(datetime64),
    min(int64),
    max(int64),
    round(avg(int64), 5),
    sum(int64),
    min(int32),
    max(int32),
    round(avg(int32), 5),
    sum(int32),
    min(int16),
    max(int16),
    round(avg(int16), 5),
    sum(int16),
    min(int8),
    max(int8),
    round(avg(int8), 5),
    sum(int8)
FROM testNullableStates
GROUP BY id
ORDER BY id ASC;

SELECT
    id,
    count(),
    minMerge(stringMin),
    maxMerge(stringMax),
    round(minMerge(float64Min), 5),
    round(maxMerge(float64Max), 5),
    round(avgMerge(float64Avg), 5),
    round(sumMerge(float64Sum), 5),
    round(minMerge(float32Min), 5),
    round(maxMerge(float32Max), 5),
    round(avgMerge(float32Avg), 5),
    round(sumMerge(float32Sum), 5),
    minMerge(decimal325Min),
    maxMerge(decimal325Max),
    round(avgMerge(decimal325Avg), 5),
    sumMerge(decimal325Sum),
    minMerge(dateMin),
    maxMerge(dateMax),
    minMerge(datetimeMin),
    maxMerge(datetimeMax),
    minMerge(datetime64Min),
    maxMerge(datetime64Max),
    minMerge(int64Min),
    maxMerge(int64Max),
    round(avgMerge(int64Avg), 5),
    sumMerge(int64Sum),
    minMerge(int32Min),
    maxMerge(int32Max),
    round(avgMerge(int32Avg), 5),
    sumMerge(int32Sum),
    minMerge(int16Min),
    maxMerge(int16Max),
    round(avgMerge(int16Avg), 5),
    sumMerge(int16Sum),
    minMerge(int8Min),
    maxMerge(int8Max),
    round(avgMerge(int8Avg), 5),
    sumMerge(int8Sum)
FROM testNullableStatesAgg
GROUP BY id
ORDER BY id ASC;

SELECT
    id,
    count(),
    min(string),
    max(string),
    round(min(float64), 5),
    round(max(float64), 5),
    round(avg(float64), 5),
    round(sum(float64), 5),
    round(min(float32), 5),
    round(max(float32), 5),
    round(avg(float32), 5),
    round(sum(float32), 5),
    min(decimal325),
    max(decimal325),
    round(avg(decimal325), 5),
    sum(decimal325),
    min(date),
    max(date),
    min(datetime),
    max(datetime),
    min(datetime64),
    max(datetime64),
    min(int64),
    max(int64),
    round(avg(int64), 5),
    sum(int64),
    min(int32),
    max(int32),
    round(avg(int32), 5),
    sum(int32),
    min(int16),
    max(int16),
    round(avg(int16), 5),
    sum(int16),
    min(int8),
    max(int8),
    round(avg(int8), 5),
    sum(int8)
FROM testNullableStates
WHERE id = '-2'
GROUP BY id
ORDER BY id ASC;

SELECT
    id,
    count(),
    minMerge(stringMin),
    maxMerge(stringMax),
    round(minMerge(float64Min), 5),
    round(maxMerge(float64Max), 5),
    round(avgMerge(float64Avg), 5),
    round(sumMerge(float64Sum), 5),
    round(minMerge(float32Min), 5),
    round(maxMerge(float32Max), 5),
    round(avgMerge(float32Avg), 5),
    round(sumMerge(float32Sum), 5),
    minMerge(decimal325Min),
    maxMerge(decimal325Max),
    round(avgMerge(decimal325Avg), 5),
    sumMerge(decimal325Sum),
    minMerge(dateMin),
    maxMerge(dateMax),
    minMerge(datetimeMin),
    maxMerge(datetimeMax),
    minMerge(datetime64Min),
    maxMerge(datetime64Max),
    minMerge(int64Min),
    maxMerge(int64Max),
    round(avgMerge(int64Avg), 5),
    sumMerge(int64Sum),
    minMerge(int32Min),
    maxMerge(int32Max),
    round(avgMerge(int32Avg), 5),
    sumMerge(int32Sum),
    minMerge(int16Min),
    maxMerge(int16Max),
    round(avgMerge(int16Avg), 5),
    sumMerge(int16Sum),
    minMerge(int8Min),
    maxMerge(int8Max),
    round(avgMerge(int8Avg), 5),
    sumMerge(int8Sum)
FROM testNullableStatesAgg
WHERE id = '-2'
GROUP BY id
ORDER BY id ASC;

SELECT
    count(),
    min(string),
    max(string),
    round(min(float64), 5),
    round(max(float64), 5),
    round(avg(float64), 5),
    round(sum(float64), 5),
    round(min(float32), 5),
    round(max(float32), 5),
    round(avg(float32), 5),
    round(sum(float32), 5),
    min(decimal325),
    max(decimal325),
    round(avg(decimal325), 5),
    sum(decimal325),
    min(date),
    max(date),
    min(datetime),
    max(datetime),
    min(datetime64),
    max(datetime64),
    min(int64),
    max(int64),
    round(avg(int64), 5),
    sum(int64),
    min(int32),
    max(int32),
    round(avg(int32), 5),
    sum(int32),
    min(int16),
    max(int16),
    round(avg(int16), 5),
    sum(int16),
    min(int8),
    max(int8),
    round(avg(int8), 5),
    sum(int8)
FROM testNullableStates
WHERE id = '-22';

SELECT
    count(),
    minMerge(stringMin),
    maxMerge(stringMax),
    round(minMerge(float64Min), 5),
    round(maxMerge(float64Max), 5),
    round(avgMerge(float64Avg), 5),
    round(sumMerge(float64Sum), 5),
    round(minMerge(float32Min), 5),
    round(maxMerge(float32Max), 5),
    round(avgMerge(float32Avg), 5),
    round(sumMerge(float32Sum), 5),
    minMerge(decimal325Min),
    maxMerge(decimal325Max),
    round(avgMerge(decimal325Avg), 5),
    sumMerge(decimal325Sum),
    minMerge(dateMin),
    maxMerge(dateMax),
    minMerge(datetimeMin),
    maxMerge(datetimeMax),
    minMerge(datetime64Min),
    maxMerge(datetime64Max),
    minMerge(int64Min),
    maxMerge(int64Max),
    round(avgMerge(int64Avg), 5),
    sumMerge(int64Sum),
    minMerge(int32Min),
    maxMerge(int32Max),
    round(avgMerge(int32Avg), 5),
    sumMerge(int32Sum),
    minMerge(int16Min),
    maxMerge(int16Max),
    round(avgMerge(int16Avg), 5),
    sumMerge(int16Sum),
    minMerge(int8Min),
    maxMerge(int8Max),
    round(avgMerge(int8Avg), 5),
    sumMerge(int8Sum)
FROM testNullableStatesAgg
WHERE id = '-22';