SELECT * FROM test ORDER BY i; -- 5 rows
SELECT * FROM test ORDER BY i OFFSET 20; -- 5 rows
SELECT * FROM (SELECT i FROM test ORDER BY i LIMIT 10 OFFSET 50) TMP ORDER BY i; -- 5 rows
SELECT * FROM test ORDER BY i LIMIT 4 OFFSET 192; -- 4 rows
SELECT * FROM test ORDER BY i LIMIT 10 OFFSET 195; -- 5 rows
SELECT * FROM test ORDER BY i LIMIT 2*2 OFFSET 192;
SELECT * FROM test ORDER BY i LIMIT 100; -- no result
SELECT * FROM test ORDER BY i LIMIT 20 OFFSET 100; -- 10 rows
SELECT * FROM test ORDER BY i LIMIT 11 OFFSET 100; -- 1 rows
SELECT * FROM test ORDER BY i LIMIT 20 OFFSET 10*10;
SELECT * FROM test ORDER BY i LIMIT 4*5 OFFSET 10*10;
SELECT * FROM test ORDER BY i LIMIT 50 OFFSET 50; -- 10 rows
SELECT * FROM test ORDER BY i LIMIT 50 OFFSET 190; -- 0 rows
SELECT * FROM test ORDER BY i LIMIT 50 OFFSET 185; -- 5 rows
SELECT * FROM test ORDER BY i LIMIT 18 OFFSET 5; -- 8 rows
