SELECT DIV AS MOD FROM (SELECT 1 `DIV`) FORMAT TSVWithNames;
SELECT DIV `MOD` FROM (SELECT 1 `DIV`) FORMAT TSVWithNames;
SELECT DIV MOD 1 FROM (SELECT 1 `DIV`) FORMAT TSVWithNames;
SELECT 1 DIV `MOD` `DIV` FROM (SELECT 1 `MOD`) FORMAT TSVWithNames;
