DROP TABLE IF EXISTS tp;

CREATE TABLE tp
(
    x Int32,
    y Int32,
    PROJECTION p (    SELECT
        x,
        y
    ORDER BY x ASC)
)
ENGINE = MergeTree
ORDER BY y;

ALTER TABLE tp DROP PROJECTION pp; -- { serverError NO_SUCH_PROJECTION_IN_TABLE }

ALTER TABLE tp DROP PROJECTION pp;

ALTER TABLE tp DROP PROJECTION p;

ALTER TABLE tp DROP PROJECTION p; -- { serverError NO_SUCH_PROJECTION_IN_TABLE }

DROP TABLE tp;