DROP TABLE IF EXISTS sales;

CREATE TABLE sales
(
    DATE_SOLD DateTime64(3, 'UTC'),
    PRODUCT_ID Nullable(String)
)
ENGINE = MergeTree()
ORDER BY DATE_SOLD
PARTITION BY toYYYYMM(DATE_SOLD);

ALTER TABLE sales ADD PROJECTION test (SELECT toInt64(COUNT(*))
GROUP BY
    PRODUCT_ID,
    DATE_SOLD);

SHOW CREATE TABLE sales;

DROP TABLE sales;