create table test1 (i int, j int) engine MergeTree partition by i order by tuple() settings index_granularity = 1;
select count() from test1 where not has([1,2,3], i);
select count() from test1 where i not in (1,2,3);
set max_rows_to_read = 5;
select * from test1 where not has([1,2,3,4,5], i) order by i;
select * from test1 where i not in (1,2,3,4,5) order by i;
create table t1 (date Date, a Float64, b String) Engine=MergeTree ORDER BY date;
create table t2 (date Date, a Float64, b String) Engine=MergeTree ORDER BY date;
select date, a, b from t1 where not has((select groupUniqArray(tuple(date, a, b)) from t2), tuple(date, a, b));
select date, a, b from t2 where not has((select groupUniqArray(tuple(date, a, b)) from t1), tuple(date, a, b));
select date, a, b from t1 where (date, a, b) NOT IN (select date,a,b from t2);
select date, a, b from t2 where (date, a, b) NOT IN (select date,a,b from t1);
