CREATE TABLE t_inter_02233
(
    n Int32
)
ENGINE = MergeTree
ORDER BY n;

INSERT INTO t_inter_02233;

SELECT
    n,
    count() AS m
FROM t_inter_02233
GROUP BY n
ORDER BY n ASC WITH FILL INTERPOLATE (m AS m + 1);

SYSTEM DROP  TABLE IF EXISTS t_inter_02233;