DROP TABLE IF EXISTS merge_table_standard_delete;
CREATE TABLE merge_table_standard_delete(id Int32, name String) ENGINE = MergeTree order by id settings min_bytes_for_wide_part=10000000;
INSERT INTO merge_table_standard_delete select number, toString(number) from numbers(100);
SELECT COUNT(), part_type FROM system.parts WHERE database = currentDatabase() AND table = 'merge_table_standard_delete' AND active GROUP BY part_type ORDER BY part_type;
SET mutations_sync = 0;
SET check_query_single_value_result = 1;
SELECT COUNT() FROM merge_table_standard_delete;
DROP TABLE merge_table_standard_delete;
drop table if exists t_light;
create table t_light(a int, b int, c int, index i_c(b) type minmax granularity 4) engine = MergeTree order by a partition by c % 5 settings min_bytes_for_wide_part=10000000;
INSERT INTO t_light SELECT number, number, number FROM numbers(10);
SELECT COUNT(), part_type FROM system.parts WHERE database = currentDatabase() AND table = 't_light' AND active GROUP BY part_type ORDER BY part_type;
SELECT '-----lightweight mutation type-----';
alter table t_light MATERIALIZE INDEX i_c SETTINGS mutations_sync=2;
alter table t_light update b=-1 where a<3 SETTINGS mutations_sync=2;
alter table t_light drop index i_c SETTINGS mutations_sync=2;
SELECT command, is_done FROM system.mutations WHERE database = currentDatabase() AND table = 't_light';
select count(*) from t_light;
select * from t_light order by a;
select table, partition, name, rows from system.parts where database = currentDatabase() AND active and table ='t_light' order by name;
select table, partition, name, rows from system.parts where database = currentDatabase() AND active and table ='t_light' and rows > 0 order by name;
drop table t_light;
CREATE TABLE t_large(a UInt32, b int) ENGINE=MergeTree order BY a settings min_bytes_for_wide_part=0, index_granularity=8192, index_granularity_bytes='10Mi';
INSERT INTO t_large SELECT number + 1, number + 1  FROM numbers(100000);
ALTER TABLE t_large UPDATE b = -2 WHERE a between 1000 and 1005 SETTINGS mutations_sync=2;
ALTER TABLE t_large DELETE WHERE a=1 SETTINGS mutations_sync=2;
SELECT * FROM t_large WHERE a in (1,1000,1005,50000) order by a;
DROP TABLE  t_large;
