-- Tags: no-fasttest

set input_format_json_try_infer_numbers_from_strings=1;
set input_format_json_read_numbers_as_strings=0;
set input_format_json_infer_array_of_dynamic_from_array_of_different_types=0;
