SELECT count() FROM hits_text WHERE hasToken(SearchPhrase, 'video');
SELECT count() FROM hits_text WHERE hasToken(SearchPhrase, 'google');
SELECT count() FROM hits_text WHERE hasToken(SearchPhrase, 'market');
SELECT count() FROM hits_text WHERE hasToken(SearchPhrase, 'world');
SELECT count() FROM hits_text WHERE hasToken(SearchPhrase, 'mail');
SELECT count() FROM hits_text WHERE hasToken(SearchPhrase, 'amazon');
SELECT uniqExact(UserID) FROM hits_text WHERE hasToken(SearchPhrase, 'anime');
SELECT count() FROM hits_text WHERE hasToken(URL, 'com');
SELECT count() FROM hits_text WHERE hasToken(URL, 'com') AND hasToken(URL, 'mail');
SELECT count() FROM hits_text WHERE hasToken(URL, 'com') AND NOT hasToken(URL, 'mail');
SELECT count() FROM hits_text WHERE hasToken(URL, 'http');
SELECT count() FROM hits_text WHERE hasToken(URL, 'https');
SELECT count() FROM hits_text WHERE hasToken(URL, 'https') AND CounterID = 33290414;
SELECT count() FROM hits_text WHERE (hasToken(URL, 'https') OR UserID = 7541501) AND CounterID = 33290414;
SELECT uniqExact(UserID), min(EventDate), max(EventDate) FROM hits_text WHERE hasToken(URL, 'https') AND hasToken(SearchPhrase, 'video');
SELECT count() FROM hits_text WHERE hasToken(URL, 'auto') AND hasToken(SearchPhrase, 'bmw');
SELECT count() FROM hits_text WHERE hasAnyTokens(URL, ['https', 'http']);
SELECT count() FROM hits_text WHERE hasAllTokens(URL, ['com', 'mail']);
SELECT count() FROM hits_text WHERE hasAllTokens(URL, ['com', 'mail']) AND NOT hasToken(URL, 'http');
SELECT count() FROM hits_text WHERE hasAnyTokens(URL, ['facebook', 'twitter']);
SELECT count() FROM hits_text WHERE hasToken(URL, 'auto') AND hasAnyTokens(SearchPhrase, ['bmw', 'audi', 'toyota']);
SELECT count() FROM hits_text WHERE hasAnyTokens(URL, ['market', 'shop']) OR hasAnyTokens(SearchPhrase, ['market', 'shop']);
