-- Tags: no-parallel, no-random-merge-tree-settings, long
DROP TABLE IF EXISTS pr_t;

DROP TABLE IF EXISTS dist_t_different_dbs;

DROP TABLE IF EXISTS shard_1.t_different_dbs;

DROP TABLE IF EXISTS t_different_dbs;

DROP TABLE IF EXISTS dist_t;

DROP TABLE IF EXISTS t;

SET optimize_trivial_insert_select = 1;

CREATE TABLE t
(
    a UInt64,
    b UInt64
)
ENGINE = MergeTree
ORDER BY a;

INSERT INTO t SELECT
    number,
    number
FROM numbers_mt(1e6);

SET enable_memory_bound_merging_of_aggregation_results = 1;

SET max_threads = 4;

SET optimize_aggregation_in_order = 1;

SET optimize_read_in_order = 1;

SET prefer_localhost_replica = 1;

-- slightly different transforms will be generated by reading steps if we let settings randomisation to change this setting value --
SET read_in_order_two_level_merge_threshold = 1000;

CREATE TABLE dist_t AS t
ENGINE = Distributed(test_cluster_two_shards, currentDatabase(), t, a % 2);

SELECT a
FROM remote(test_cluster_two_shards, currentDatabase(), t)
GROUP BY a
ORDER BY a ASC
LIMIT 5
OFFSET 100500;

SELECT a
FROM remote(test_cluster_two_shards, currentDatabase(), dist_t)
GROUP BY a
ORDER BY a ASC
LIMIT 5
OFFSET 100500;

-- { echoOff } --
SET aggregation_in_order_max_block_bytes = '1Mi';

SET max_block_size = 500;

-- actual block size might be slightly bigger than the limit --
SELECT max(bs) < 70000
FROM (
        SELECT
            avg(a),
            max(blockSize()) AS bs
        FROM remote(test_cluster_two_shards, currentDatabase(), t)
        GROUP BY a
    );

-- beautiful case when we have different sorting key definitions in tables involved in distributed query => different plans => different sorting properties of local aggregation results --
CREATE DATABASE IF NOT EXISTS shard_1;

CREATE TABLE t_different_dbs
(
    a UInt64,
    b UInt64
)
ENGINE = MergeTree
ORDER BY a;

CREATE TABLE shard_1.t_different_dbs
(
    a UInt64,
    b UInt64
)
ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO t_different_dbs SELECT
    number % 1000,
    number % 1000
FROM numbers_mt(1e6);

INSERT INTO shard_1.t_different_dbs SELECT
    number % 1000,
    number % 1000
FROM numbers_mt(1e6);

CREATE TABLE dist_t_different_dbs AS t
ENGINE = Distributed(test_cluster_two_shards_different_databases_with_local, '', t_different_dbs);

SELECT
    a,
    count()
FROM dist_t_different_dbs
GROUP BY a
ORDER BY a ASC
LIMIT 5
OFFSET 500;

SELECT
    a,
    count()
FROM dist_t_different_dbs
GROUP BY
    a,
    b
ORDER BY a ASC
LIMIT 5
OFFSET 500;

CREATE TABLE pr_t
(
    a UInt64,
    b UInt64
)
ENGINE = MergeTree
ORDER BY a;

INSERT INTO pr_t SELECT
    number % 1000,
    number % 1000
FROM numbers_mt(1e6);

SET enable_parallel_replicas = 1;

SET parallel_replicas_for_non_replicated_merge_tree = 1;

SET max_parallel_replicas = 3;

SET cluster_for_parallel_replicas = 'test_cluster_one_shard_three_replicas_localhost';

SET distributed_aggregation_memory_efficient = 1;

SET parallel_replicas_only_with_analyzer = 0; -- necessary for CI run with disabled analyzer

SELECT count()
FROM pr_t;

SELECT
    a,
    count()
FROM pr_t
GROUP BY a
ORDER BY a ASC
LIMIT 5
OFFSET 500;

SELECT
    a,
    count()
FROM pr_t
GROUP BY
    a,
    b
ORDER BY a ASC
LIMIT 5
OFFSET 500;