CREATE TABLE a (k UInt64, a1 UInt64, a2 String) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO a VALUES (1, 1, 'a'), (2, 2, 'b'), (3, 3, 'c');
CREATE TABLE b (k UInt64, b1 UInt64, b2 String) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO b VALUES (1, 1, 'a'), (2, 2, 'b'), (3, 3, 'c');
CREATE TABLE c (k UInt64, c1 UInt64, c2 String) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO c VALUES (1, 1, 'a'), (2, 2, 'b'), (3, 3, 'c');
CREATE TABLE d (k UInt64, d1 UInt64, d2 String) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO d VALUES (1, 1, 'a'), (2, 2, 'b'), (3, 3, 'c');
SET enable_analyzer = 1;
SET query_plan_join_swap_table = 'false';
SET enable_parallel_replicas = 0;
SET query_plan_optimize_join_order_limit = 2;
SET optimize_empty_string_comparisons=0;
SET enable_join_runtime_filters=0;
