-- Tags: no-object-storage
SET merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0.0;

DROP TABLE IF EXISTS t;

CREATE TABLE t
(
    a UInt64
)
ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO t SELECT *
FROM numbers_mt(1e3);

SET allow_asynchronous_read_from_io_pool_for_merge_tree = 1;

SET max_streams_for_merge_tree_reading = 64;

SET max_block_size = 65409;

-- slightly different transforms will be generated by reading steps if we let settings randomisation to change this setting value --
SET read_in_order_two_level_merge_threshold = 1000;