DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE:Identifier};

CREATE DATABASE IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier};

CREATE TABLE IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier}.r1
(
    name String
)
ENGINE = Memory();

SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier};

RENAME TABLE {CLICKHOUSE_DATABASE:Identifier}.r1 TO {CLICKHOUSE_DATABASE:Identifier}.r1_bak;

RENAME TABLE {CLICKHOUSE_DATABASE:Identifier}.r1_bak TO {CLICKHOUSE_DATABASE:Identifier}.r1;

CREATE TABLE IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier}.r2
(
    name String
)
ENGINE = Memory();

RENAME TABLE {CLICKHOUSE_DATABASE:Identifier}.r1 TO {CLICKHOUSE_DATABASE:Identifier}.r1_bak, {CLICKHOUSE_DATABASE:Identifier}.r2 TO {CLICKHOUSE_DATABASE:Identifier}.r2_bak;

CREATE TABLE IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier}.source_table
(
    id UInt64,
    value String
)
ENGINE = Memory;

CREATE DICTIONARY IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier}.test_dictionary
(
    id UInt64,
    value String
)
PRIMARY KEY id
SOURCE(clickhouse(TABLE '{CLICKHOUSE_DATABASE:String}.dictionary_table'))
LIFETIME(MIN 0 MAX 1000)
LAYOUT(FLAT());

SHOW DICTIONARIES FROM {CLICKHOUSE_DATABASE:Identifier};

RENAME TABLE {CLICKHOUSE_DATABASE:Identifier}.test_dictionary TO {CLICKHOUSE_DATABASE:Identifier}.test_dictionary_2;

SHOW DATABASES LIKE '{CLICKHOUSE_DATABASE:String}';

RENAME TABLE {CLICKHOUSE_DATABASE:Identifier} TO {CLICKHOUSE_DATABASE_1:Identifier}; -- { serverError UNKNOWN_TABLE }