set allow_experimental_variant_type=1;
set allow_suspicious_types_in_order_by=1;
set use_variant_default_implementation_for_comparisons = 0;
create table test (v1 Variant(String, UInt64, Array(UInt32)), v2 Variant(String, UInt64, Array(UInt32))) engine=Memory;
select v1 from test order by v1 nulls first;
select v1 from test order by v1 nulls last;
select v2 from test order by v2 nulls first;
select v2 from test order by v2 nulls last;
select * from test order by v1, v2 nulls first;
select * from test order by v1, v2 nulls last;
select * from test order by v2, v1 nulls first;
select * from test order by v2, v1 nulls last;
select v1, v2, v1 = v2 from test order by v1, v2;
select v1, v2, v1 < v2 from test order by v1, v2;
select v1, v2, v1 <= v2 from test order by v1, v2;
select v1, v2, v1 > v2 from test order by v1, v2;
select v1, v2, v2 >= v2 from test order by v1, v2;
