SET merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0.0;
CREATE TABLE test_empty (a Array(Int64)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) FROM test_empty;
CREATE TABLE test_null (a Array(Nullable(Int64))) engine=MergeTree ORDER BY a SETTINGS allow_nullable_key=1;
SELECT arraySort(groupArrayIntersect(*)) FROM test_null;
CREATE TABLE test_nested_arrays (a Array(Array(Int64))) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) FROM test_nested_arrays;
CREATE TABLE test_numbers (a Array(Int64)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) FROM test_numbers;
CREATE TABLE test_big_numbers_sep (a Array(Int64)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) FROM test_big_numbers_sep;
CREATE TABLE test_big_numbers (a Array(Int64)) engine=MergeTree ORDER BY a;
SELECT length(groupArrayIntersect(*)) FROM test_big_numbers;
SELECT arraySort(groupArrayIntersect(*)) FROM test_big_numbers;
CREATE TABLE test_string (a Array(String)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) FROM test_string;
CREATE TABLE test_big_string (a Array(String)) engine=MergeTree ORDER BY a;
SELECT length(groupArrayIntersect(*)) FROM test_big_string;
SELECT arraySort(groupArrayIntersect(*)) FROM test_big_string;
CREATE TABLE test_datetime (a Array(DateTime)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) from test_datetime;
CREATE TABLE test_date32 (a Array(Date32)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) from test_date32;
CREATE TABLE test_date (a Array(Date)) engine=MergeTree ORDER BY a;
SELECT arraySort(groupArrayIntersect(*)) from test_date;
