SELECT
    O_ORDERPRIORITY,
    count(*) AS order_count
FROM
    ORDERS
INNER JOIN (
        SELECT L_ORDERKEY
        FROM LINEITEM_shard
        GROUP BY L_ORDERKEY
        HAVING any(L_COMMITDATE < L_RECEIPTDATE)
    )
    ON O_ORDERKEY = L_ORDERKEY
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY ASC
LIMIT 1;

SELECT
    O_ORDERPRIORITY,
    count(*) AS order_count
FROM
    ORDERS
INNER JOIN (
        SELECT L_ORDERKEY
        FROM LINEITEM_shard
        GROUP BY L_ORDERKEY
        HAVING any(L_COMMITDATE < L_RECEIPTDATE)
    ) AS x
    ON O_ORDERKEY = L_ORDERKEY
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY ASC
LIMIT 1;