SET enable_analyzer = 1;
create table date_table_pv (id Int32, dt Date) engine = Memory();
create view date_pv as select * from date_table_pv where dt =  {dtparam:Date};
select id from date_pv(dtparam=today());
select id from date_pv(dtparam=yesterday());
select id from date_pv(dtparam=yesterday()+1);
select id from date_pv(dtparam='1974-04-07');
select id from date_pv(dtparam=toDate('1974-04-07'));
select id from date_pv(dtparam=toString(toDate('1974-04-07')));
select id from date_pv(dtparam=toDate('1975-04-07'));
select id from date_pv(dtparam=(select dt from date_table_pv where id = 2));
create table date32_table_pv (id Int32, dt Date32) engine = Memory();
create view date32_pv as select * from date32_table_pv where dt =  {dtparam:Date32};
select id from date32_pv(dtparam=today());
select id from date32_pv(dtparam=yesterday());
select id from date32_pv(dtparam=yesterday()+1);
select id from date32_pv(dtparam='2199-12-31');
select id from date32_pv(dtparam=toDate32('1900-01-01'));
select id from date32_pv(dtparam=(select dt from date32_table_pv where id = 3));
select id from date32_pv(dtparam=(select dt from date32_table_pv where id = 4));
create table uuid_table_pv (id Int32, uu UUID) engine = Memory();
create view uuid_pv as select * from uuid_table_pv where uu =  {uuidparam:UUID};
select id from uuid_pv(uuidparam=serverUUID());
select id from uuid_pv(uuidparam=toUUID('11111111-2222-3333-4444-555555555555'));
select id from uuid_pv(uuidparam='11111111-2222-3333-4444-555555555555');
select id from uuid_pv(uuidparam=(select uu from uuid_table_pv where id = 1));
select id from uuid_pv(uuidparam=(select uu from uuid_table_pv where id = 2));
-- generateUUIDv4() is not constant foldable, hence cannot be used as parameter value
select id from uuid_pv(uuidparam=generateUUIDv4()); -- { serverError UNKNOWN_QUERY_PARAMETER }
-- But nested "select generateUUIDv4()"  works!
select id from uuid_pv(uuidparam=(select generateUUIDv4()));
create view date_pv2 as select * from date_table_pv where dt = {dtparam:Date} and id = {intparam:Int32};
select id from date_pv2(dtparam=today(),intparam=1);
select id from date_pv2(dtparam=today(),intparam=length('A'));
select id from date_pv2(dtparam='1974-04-07',intparam=length('AAA'));
select id from date_pv2(dtparam=toDate('1974-04-07'),intparam=length('BBB'));
create table ipv4_table_pv (id Int32, ipaddr IPv4) ENGINE = Memory();
create view ipv4_pv as select * from ipv4_table_pv where ipaddr = {ipv4param:IPv4};
select id from ipv4_pv(ipv4param='116.106.34.242');
select id from ipv4_pv(ipv4param=toIPv4('116.106.34.243'));
select id from ipv4_pv(ipv4param=(select ipaddr from ipv4_table_pv where id=3));
