select accurateCastOrDefault(variant, 'UInt32'), multiIf(number % 4 == 0, NULL, number % 4 == 1, number, number % 4 == 2, 'str_' || toString(number), range(number)) as variant from numbers(8);
select accurateCastOrNull(variant, 'UInt32'), multiIf(number % 4 == 0, NULL, number % 4 == 1, number, number % 4 == 2, 'str_' || toString(number), range(number)) as variant from numbers(8);
select accurateCastOrDefault(dynamic, 'UInt32'), multiIf(number % 4 == 0, NULL, number % 4 == 1, number, number % 4 == 2, 'str_' || toString(number), range(number))::Dynamic as dynamic from numbers(8);
select accurateCastOrNull(dynamic, 'UInt32'), multiIf(number % 4 == 0, NULL, number % 4 == 1, number, number % 4 == 2, 'str_' || toString(number), range(number))::Dynamic as dynamic from numbers(8);
select distinct toInt8OrDefault(d) as res from t order by res;
select distinct toUInt8OrDefault(d) as res from t order by res;
select distinct toInt16OrDefault(d) as res from t order by res;
select distinct toUInt16OrDefault(d) as res from t order by res;
select distinct toInt32OrDefault(d) as res from t order by res;
select distinct toUInt32OrDefault(d) as res from t order by res;
select distinct toInt64OrDefault(d) as res from t order by res;
select distinct toUInt64OrDefault(d) as res from t order by res;
select distinct toInt128OrDefault(d) as res from t order by res;
select distinct toUInt128OrDefault(d) as res from t order by res;
select distinct toInt256OrDefault(d) as res from t order by res;
select distinct toUInt256OrDefault(d) as res from t order by res;
select distinct toFloat32OrDefault(d) as res from t order by res;
select distinct toFloat64OrDefault(d) as res from t order by res;
select distinct toDecimal32OrDefault(d, 3) as res from t order by res;
select distinct toDecimal64OrDefault(d, 3) as res from t order by res;
select distinct toDecimal128OrDefault(d, 3) as res from t order by res;
select distinct toDecimal256OrDefault(d, 3) as res from t order by res;
select distinct toDateOrDefault(d) as res from t order by res;
select distinct toDate32OrDefault(d) as res from t order by res;
select distinct toDateTimeOrDefault(d) as res from t order by res;
select distinct toIPv4OrDefault(d) as res from t order by res;
select distinct toIPv6OrDefault(d) as res from t order by res;
select distinct toUUIDOrDefault(d) as res from t order by res;
SELECT d FROM t ORDER BY id;
