select d + 1 as res, toTypeName(res) from test;
select 1 + d as res, toTypeName(res) from test;
select d + x as res, toTypeName(res) from test;
select x + d as res, toTypeName(res) from test;
select d + d as res, toTypeName(res) from test;
select d + 1 + d as res, toTypeName(res) from test;
select d + x + d as res, toTypeName(res) from test;
select d + NULL as res, toTypeName(res) from test;
select d < 2 as res, toTypeName(res) from test;
select d < d as res, toTypeName(res) from test;
select d < x as res, toTypeName(res) from test;
select d > 2 as res, toTypeName(res) from test;
select d > d as res, toTypeName(res) from test;
select d > x as res, toTypeName(res) from test;
select d = 2 as res, toTypeName(res) from test;
select d = d as res, toTypeName(res) from test;
select d = x as res, toTypeName(res) from test;
select d = NULL as res, toTypeName(res) from test;
select * from test where d < 2;
select * from test where d > 2;
select * from test where d = 2;
select * from test where d < d;
select * from test where d > d;
select * from test where d = d;
select * from test where d < x;
select * from test where d > x;
select * from test where d = x;
select * from test where d = NULL;
select exp2(d) as res, toTypeName(res) from test;
select sin(d) as res, toTypeName(res) from test;
select cos(d) as res, toTypeName(res) from test;
select tan(d) as res, toTypeName(res) from test;
select mortonEncode(d) as res, toTypeName(res) from test;
select hilbertEncode(d) as res, toTypeName(res) from test;
select bitmaskToList(d) as res, toTypeName(res) from test;
select bitPositionsToArray(d) as res, toTypeName(res) from test;
select isFinite(d) as res, toTypeName(res) from test;
select sipHash64(d) as res, toTypeName(res) from test;
select sipHash128(d) as res, toTypeName(res) from test;
select intHash32(d) as res, toTypeName(res) from test;
select intHash64(d) as res, toTypeName(res) from test;
select h3CellAreaM2(585763170430222335 + d * 549755813888) as res, toTypeName(res) from test;
select h3CellAreaRads2(585763170430222335 + d * 549755813888) as res, toTypeName(res) from test;
select h3Distance(585763170430222335 + d * 549755813888, 585763170430222335 + (d + 1) * 549755813888) as res, toTypeName(res) from test;
select sqid(d) as res, toTypeName(res) from test;
select sipHash64(d, x) as res, toTypeName(res) from test;
select 'str_' || d as res, toTypeName(res) from test;
select 'str_' || d || x as res, toTypeName(res) from test;
select 'str_' || d || d as res, toTypeName(res) from test;
select 'str_' || d || x || d as res, toTypeName(res) from test;
select d || NULL as res, toTypeName(res) from test;
select 'str_' || d || NULL as res, toTypeName(res) from test;
select d < 'str_2' as res, toTypeName(res) from test;
select d > 'str_2' as res, toTypeName(res) from test;
select d = 'str_2' as res, toTypeName(res) from test;
select * from test where d < 'str_2';
select * from test where d > 'str_2';
select * from test where d = 'str_2';
select upper(d) as res, toTypeName(res) from test;
select appendTrailingCharIfAbsent(d, 'd') as res, toTypeName(res) from test;
select match(d, 'str') as res, toTypeName(res) from test;
select concatWithSeparator('|', d, d) as res, toTypeName(res) from test;
select extract(d, '([0-3])') as res, toTypeName(res) from test;
select startsWith(d, 'str') as res, toTypeName(res) from test;
select length(d) as res, toTypeName(res) from test;
select replaceAll(d, 'str', 'a') as res, toTypeName(res) from test;
select repeat(d, 2) as res, toTypeName(res) from test;
select substring(d, 1, 3) as res, toTypeName(res) from test;
select sipHash64(d, d) as res, toTypeName(res) from test;
select d + 1 as res, toTypeName(res), dynamicType(res) from test;
select 1 + d as res, toTypeName(res), dynamicType(res) from test;
select d + x as res, toTypeName(res), dynamicType(res) from test;
select x + d as res, toTypeName(res), dynamicType(res) from test;
select d + d as res, toTypeName(res), dynamicType(res) from test;
select d + 1 + d as res, toTypeName(res), dynamicType(res) from test;
select d + x + d as res, toTypeName(res), dynamicType(res) from test;
select d + NULL as res, toTypeName(res), dynamicType(res) from test;
select d < 5 as res, toTypeName(res) from test;
select d > 5 as res, toTypeName(res) from test;
select d = 5 as res, toTypeName(res) from test;
select * from test where d < 5;
select * from test where d > 5;
select * from test where d = 5;
select d[1] as res, toTypeName(res) from test;
select d + 1 from test; -- {serverError ILLEGAL_TYPE_OF_ARGUMENT}
select length(d) from test; -- {serverError ILLEGAL_TYPE_OF_ARGUMENT}
select d[1] from test; -- {serverError ILLEGAL_TYPE_OF_ARGUMENT}
select sipHash64(d) from test;
select sipHash64(d, 42) from test;
select sipHash64(d, d) from test;
