CREATE TABLE t0
(
    c0 Int
)
ENGINE = Memory();

SELECT 1
FROM
    t0
INNER JOIN t0
    ON *; -- { serverError BAD_ARGUMENTS,INVALID_JOIN_ON_EXPRESSION }

SELECT 1
FROM
    t0
INNER JOIN t0
    ON tuple(*); -- { serverError AMBIGUOUS_COLUMN_NAME,ILLEGAL_TYPE_OF_ARGUMENT }

SELECT 1
FROM
    t0
INNER JOIN t0
    USING *; -- { serverError BAD_ARGUMENTS,UNSUPPORTED_JOIN_KEYS }