DROP TABLE IF EXISTS t;
DROP TABLE IF EXISTS t2;
CREATE TABLE t (x int) ENGINE = MergeTree() ORDER BY ();
ALTER TABLE t DELETE WHERE x in (SELECT y FROM t); -- { serverError UNKNOWN_IDENTIFIER }
ALTER TABLE t UPDATE x = 1 WHERE x IN (SELECT y FROM t); -- { serverError UNKNOWN_IDENTIFIER }
ALTER TABLE t ADD COLUMN y int;
CREATE TABLE t2 (x int) ENGINE = MergeTree() ORDER BY ();
DROP TABLE t;
DROP TABLE t2;
