DROP TABLE IF EXISTS test;
CREATE TABLE test (x UInt8, y UInt8, z String DEFAULT toString(x)) PARTITION BY x ORDER BY x;
INSERT INTO test (x, y) VALUES (1, 1);
INSERT INTO test (x, y) VALUES (1, 2);
INSERT INTO test (x, y) VALUES (2, 1);
SET mutations_sync = 1;
SELECT * FROM test ORDER BY ALL;
DROP TABLE test SYNC;
-- SELECT * FROM system.part_log WHERE database = currentDatabase() FORMAT Vertical;
SELECT DISTINCT throwIf(empty(partition)) FROM system.part_log WHERE database = currentDatabase();
