CREATE TABLE IF NOT EXISTS test
(
    a UInt64
)
ENGINE = MergeTree()
ORDER BY a;

INSERT INTO test (a) SELECT 1
FROM numbers(1000);

SYSTEM DROP  TABLE IF EXISTS test;

CREATE TABLE IF NOT EXISTS tab
(
    x UInt32,
    y UInt32
)
ENGINE = MergeTree
ORDER BY tuple();

CREATE DICTIONARY IF NOT EXISTS dict
(
    x UInt32,
    y UInt32
)
PRIMARY KEY x
SOURCE(clickhouse(table 'tab'))
LIFETIME(MIN 0 MAX 1000)
LAYOUT(FLAT());

INSERT INTO tab;

CREATE TABLE IF NOT EXISTS tab2
(
    x UInt32,
    y UInt32 MATERIALIZED dictGet(dict, 'y', x)
)
ENGINE = MergeTree
ORDER BY (y);

INSERT INTO tab2 (x);

INSERT INTO tab;

SET mutations_sync = 2;

SYSTEM DROP  TABLE IF EXISTS tab2;

SYSTEM DROP  DICTIONARY IF EXISTS dict;

SYSTEM DROP  TABLE IF EXISTS tab;