SET enable_json_type = 1;
set output_format_native_write_json_as_string = 0;
create table test (json JSON(max_dynamic_paths=8, max_dynamic_types=4)) engine=Memory;
select arrayJoin(distinctJSONPathsAndTypes(json)) from test;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k1[]))) from test;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k2[]))) from test;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k9[]))) from test;
select json.k1[], json.k1[].k1_1[], json.k1[].k1_1[].k1_1_1, json.k1[].k1_2[], json.k1[].k1_2[].k1_2_1, json.k2[], json.k2[].k2_1[], json.k2[].k2_1[].k2_1_1, json.k2[].k2_2[], json.k2[].k2_2[].k2_2_1, json.k9[], json.k9[].k9_1[], json.k9[].k9_1[].k9_1_1, json.k9[].k9_2[], json.k9[].k9_2[].k9_2_1 from test format JSONColumns;
create table test2 (json JSON(max_dynamic_paths=16, max_dynamic_types=8)) engine=Memory;
select arrayJoin(distinctJSONPathsAndTypes(json)) from test2;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k1[]))) from test2;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k2[]))) from test2;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k9[]))) from test2;
create table test3 (json JSON(max_dynamic_paths=4, max_dynamic_types=2)) engine=Memory;
select arrayJoin(distinctJSONPathsAndTypes(json)) from test3;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k1[]))) from test3;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k2[]))) from test3;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k9[]))) from test3;
create table test4 (json JSON(max_dynamic_paths=8, max_dynamic_types=4)) engine=Memory;
select arrayJoin(distinctJSONPathsAndTypes(json)) from test4;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k1[]))) from test4;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k2[]))) from test4;
select arrayJoin(distinctJSONPathsAndTypes(arrayJoin(json.k9[]))) from test4;
