SELECT *
FROM
    T1
FULL JOIN T2
    ON T1.A = T2.A
ORDER BY `ALL` ASC
FORMAT PrettyCompactMonoBlock;

SELECT *
FROM
    T1
FULL JOIN T2
    USING (A)
ORDER BY `ALL` ASC
FORMAT PrettyCompactMonoBlock;

SELECT *
FROM
    T1
FULL JOIN {CLICKHOUSE_DATABASE:Identifier}.T2
    ON T1.A = T2.A
ORDER BY `ALL` ASC
FORMAT PrettyCompactMonoBlock;

SELECT *
FROM
    {CLICKHOUSE_DATABASE:Identifier}.T1
FULL JOIN T2
    ON T1.A = T2.A
ORDER BY `ALL` ASC
FORMAT PrettyCompactMonoBlock;