CREATE DICTIONARY dict (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(BLOCK_SIZE -1)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }
CREATE DICTIONARY dict (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(COMPLEX_KEY_SSD_CACHE(BLOCK_SIZE -1)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }
CREATE DICTIONARY dict (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(BLOCK_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }
CREATE DICTIONARY dict (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(COMPLEX_KEY_SSD_CACHE(BLOCK_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }
CREATE DICTIONARY dict (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(WRITE_BUFFER_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }
CREATE DICTIONARY dict (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(COMPLEX_KEY_SSD_CACHE(WRITE_BUFFER_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }
