CREATE DICTIONARY dict
(
    col Int64 DEFAULT NULL
)
PRIMARY KEY (col)
SOURCE(null())
LIFETIME(1)
LAYOUT(SSD_CACHE(BLOCK_SIZE -1)); -- { serverError BAD_ARGUMENTS }

CREATE DICTIONARY dict
(
    col Int64 DEFAULT NULL
)
PRIMARY KEY (col)
SOURCE(null())
LIFETIME(1)
LAYOUT(COMPLEX_KEY_SSD_CACHE(BLOCK_SIZE -1)); -- { serverError BAD_ARGUMENTS }

CREATE DICTIONARY dict
(
    col Int64 DEFAULT NULL
)
PRIMARY KEY (col)
SOURCE(null())
LIFETIME(1)
LAYOUT(SSD_CACHE(BLOCK_SIZE 0)); -- { serverError BAD_ARGUMENTS }

CREATE DICTIONARY dict
(
    col Int64 DEFAULT NULL
)
PRIMARY KEY (col)
SOURCE(null())
LIFETIME(1)
LAYOUT(COMPLEX_KEY_SSD_CACHE(BLOCK_SIZE 0)); -- { serverError BAD_ARGUMENTS }

CREATE DICTIONARY dict
(
    col Int64 DEFAULT NULL
)
PRIMARY KEY (col)
SOURCE(null())
LIFETIME(1)
LAYOUT(SSD_CACHE(WRITE_BUFFER_SIZE 0)); -- { serverError BAD_ARGUMENTS }

CREATE DICTIONARY dict
(
    col Int64 DEFAULT NULL
)
PRIMARY KEY (col)
SOURCE(null())
LIFETIME(1)
LAYOUT(COMPLEX_KEY_SSD_CACHE(WRITE_BUFFER_SIZE 0)); -- { serverError BAD_ARGUMENTS }