DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE:Identifier};

CREATE DATABASE IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier}
ENGINE = Memory;

DROP TABLE IF EXISTS {CLICKHOUSE_DATABASE:Identifier}.v0;

CREATE MATERIALIZED VIEW {CLICKHOUSE_DATABASE:Identifier}.v0
REFRESH AFTER 1 SECOND APPEND
ENGINE = MergeTree()
ORDER BY tuple()
AS
(SELECT 1 AS c0);

ALTER TABLE {CLICKHOUSE_DATABASE:Identifier}.v0 MODIFY REFRESH AFTER 1 SECOND APPEND;