CREATE DATABASE IF NOT EXISTS {CLICKHOUSE_DATABASE:Identifier} ENGINE = Memory;
CREATE MATERIALIZED VIEW {CLICKHOUSE_DATABASE:Identifier}.v0 REFRESH AFTER 1 SECOND APPEND ENGINE = MergeTree() ORDER BY tuple() AS (SELECT 1 c0);
