select a from test_merge order by all;
select b from test_merge order by all;
select c from test_merge order by all;
select d from test_merge order by all;
select e from test_merge order by all;
select a, b from test_merge order by all;
select a, c from test_merge order by all;
select a, d from test_merge order by all;
select a, e from test_merge order by all;
select b, c from test_merge order by all;
select b, d from test_merge order by all;
select b, e from test_merge order by all;
select c, d from test_merge order by all;
select c, e from test_merge order by all;
select a, b, c from test_merge order by all;
select a, b, d from test_merge order by all;
select a, b, e from test_merge order by all;
select a, c, d from test_merge order by all;
select a, c, e from test_merge order by all;
select b, c, d from test_merge order by all;
select b, c, e from test_merge order by all;
select c, d, e from test_merge order by all;
select b, _table from test_merge order by all;
select c, _table from test_merge order by all;
select d, _table from test_merge order by all;
select e, _table from test_merge order by all;
select b, c, _table from test_merge order by all;
select b, d, _table from test_merge order by all;
select b, e, _table from test_merge order by all;
select c, d, _table from test_merge order by all;
select c, e, _table from test_merge order by all;
select d, e, _table from test_merge order by all;
