DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE:Identifier};

CREATE DATABASE {CLICKHOUSE_DATABASE:Identifier}
ENGINE = Atomic;

USE {CLICKHOUSE_DATABASE:Identifier};

CREATE TABLE data
(
    id UInt64
)
ENGINE = MergeTree()
ORDER BY id;

CREATE MATERIALIZED VIEW mv1
(
    id UInt64
)
ENGINE = MergeTree()
ORDER BY id
AS
SELECT id + 1 AS id
FROM data;

INSERT INTO data;

SELECT *
FROM mv1;

ALTER TABLE mv1 MODIFY COMMENT 'TEST COMMENT';

DROP DATABASE {CLICKHOUSE_DATABASE:Identifier};

CREATE MATERIALIZED VIEW mv1
(
    id UInt64
)
ENGINE = MergeTree()
ORDER BY id
AS
SELECT id + 2 AS id
FROM data;

DROP DATABASE {CLICKHOUSE_DATABASE_1:Identifier};

CREATE MATERIALIZED VIEW mv1
(
    id UInt64
)
ENGINE = MergeTree()
ORDER BY id
AS
SELECT id + 3 AS id
FROM data;