create table test_compact_map (json JSON(max_dynamic_paths=8)) engine=MergeTree order by tuple() settings min_bytes_for_wide_part='200G', min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map', object_shared_data_serialization_version_for_zero_level_parts='map';
select json from test_compact_map format Null;
select json.b from test_compact_map format Null;
select json.b, json.c from test_compact_map format Null;
select json, json.b, json.c from test_compact_map format Null;
select json.b, json.c, json from test_compact_map format Null;
select json.^a from test_compact_map format Null;
select json, json.^a from test_compact_map format Null;
select json.^a, json.a.a1 from test_compact_map format Null;
select json.a.a1, json.^a from test_compact_map format Null;
create table test_compact_map_tuple (json Tuple(data JSON(max_dynamic_paths=8))) engine=MergeTree order by tuple() settings min_bytes_for_wide_part='200G', min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map', object_shared_data_serialization_version_for_zero_level_parts='map';
select json.data from test_compact_map_tuple format Null;
select json.data, json.data.b from test_compact_map_tuple format Null;
select json.data.b, json.data from test_compact_map_tuple format Null;
select json.data, json.data.b, json.data.c from test_compact_map_tuple format Null;
select json.data.b, json.data, json.data.c from test_compact_map_tuple format Null;
select json.data.b, json.data.c, json.data from test_compact_map_tuple format Null;
select json.data, json.data.^a from test_compact_map_tuple format Null;
select json.data.^a, json.data from test_compact_map_tuple format Null;
select json.data, json.data.^a, json.data.b from test_compact_map_tuple format Null;
select json.data.b, json.data.^a, json.data from test_compact_map_tuple format Null;
