create table test_wide_map_with_buckets (json JSON(max_dynamic_paths=8)) engine=MergeTree order by tuple() settings min_bytes_for_wide_part=1, min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map_with_buckets', object_shared_data_serialization_version_for_zero_level_parts='map_with_buckets', object_shared_data_buckets_for_wide_part=2;
select json from test_wide_map_with_buckets format Null;
select json.b from test_wide_map_with_buckets format Null;
select json.arr from test_wide_map_with_buckets format Null;
select json.b, json.c from test_wide_map_with_buckets format Null;
select json.b, json.c, json.arr from test_wide_map_with_buckets format Null;
select json, json.b, json.c from test_wide_map_with_buckets format Null;
select json, json.b, json.c, json.arr from test_wide_map_with_buckets format Null;
select json.b, json.c, json from test_wide_map_with_buckets format Null;
select json.b, json.c, json.arr, json from test_wide_map_with_buckets format Null;
select json.^a from test_wide_map_with_buckets format Null;
select json, json.^a from test_wide_map_with_buckets format Null;
select json.^a, json.a.a1 from test_wide_map_with_buckets format Null;
select json.a.a1, json.^a from test_wide_map_with_buckets format Null;
select json.^a, json.a.a1, json.arr from test_wide_map_with_buckets format Null;
select json.a.a1, json.arr, json.^a from test_wide_map_with_buckets format Null;
