-- Tags: long, no-azure-blob-storage

set output_format_json_quote_64bit_integers=0;
create table source (json JSON(max_dynamic_paths=8)) engine=Memory;
create table test_wide_advanced (json JSON(max_dynamic_paths=8)) engine=MergeTree order by tuple() settings index_granularity=2, min_bytes_for_wide_part=1, min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='advanced', object_shared_data_serialization_version_for_zero_level_parts='advanced', object_shared_data_buckets_for_wide_part=2;
select json from test_wide_advanced;
select json.b from test_wide_advanced;
select json.b, json.c from test_wide_advanced;
select json.arr[].arr1 from test_wide_advanced;
select json.arr[].arr1, json.arr[].arr2 from test_wide_advanced;
select json.arr[].arr2, json.arr[].arr1 from test_wide_advanced;
select json.arr[].arr1, json.arr[].arr4 from test_wide_advanced;
select json.arr[].arr4, json.arr[].arr1 from test_wide_advanced;
select json.arr[].arr1, json.arr[].arr99 from test_wide_advanced;
select json.arr[].arr99, json.arr[].arr1 from test_wide_advanced;
select json.arr, json.arr[].arr1 from test_wide_advanced;
select json.arr[].arr1, json.arr from test_wide_advanced;
select json, json.b, json.c from test_wide_advanced;
select json.b, json.c, json from test_wide_advanced;
select json, json.b, json.c, json.arr[].arr1 from test_wide_advanced;
select json.b, json.c, json.arr[].arr1, json from test_wide_advanced;
select json, json.b, json.c, json.arr, json.arr[].arr1 from test_wide_advanced;
select json.b, json.c, json.arr[].arr1, json.arr, json from test_wide_advanced;
select json.^a from test_wide_advanced;
select json, json.^a from test_wide_advanced;
select json.^a, json.a.a1 from test_wide_advanced;
select json.a.a1, json.^a from test_wide_advanced;
select json.^a, json.a.a1, json.a.arr[].arr1 from test_wide_advanced;
select json.a.a1, json.a.arr[].arr1, json.^a from test_wide_advanced;
select json, json.a.a1, json.a.arr[].arr1, json.^a from test_wide_advanced;
select json.a.a1, json.a.arr[].arr1, json.^a, json from test_wide_advanced;
select json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_wide_advanced;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a from test_wide_advanced;
select json, json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_wide_advanced;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a, json from test_wide_advanced;
select json.arr[].arr1, json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_wide_advanced;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a, json.arr[].arr1 from test_wide_advanced;
select json, json.arr[].arr1, json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_wide_advanced;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a, json.arr[].arr1, json from test_wide_advanced;
