select json from test_compact_map;
select json.b from test_compact_map;
select json.b, json.c from test_compact_map;
select json, json.b, json.c from test_compact_map;
select json.b, json.c, json from test_compact_map;
select json.^a from test_compact_map;
select json, json.^a from test_compact_map;
select json.^a, json.a.a1 from test_compact_map;
select json.a.a1, json.^a from test_compact_map;
select json.data from test_compact_map_tuple;
select json.data, json.data.b from test_compact_map_tuple;
select json.data.b, json.data from test_compact_map_tuple;
select json.data, json.data.b, json.data.c from test_compact_map_tuple;
select json.data.b, json.data, json.data.c from test_compact_map_tuple;
select json.data.b, json.data.c, json.data from test_compact_map_tuple;
select json.data, json.data.^a from test_compact_map_tuple;
select json.data.^a, json.data from test_compact_map_tuple;
select json.data, json.data.^a, json.data.b from test_compact_map_tuple;
select json.data.b, json.data.^a, json.data from test_compact_map_tuple;
select json from test_wide_map;
select json.b from test_wide_map;
select json.b, json.c from test_wide_map;
select json, json.b, json.c from test_wide_map;
select json.b, json.c, json from test_wide_map;
select json.^a from test_wide_map;
select json, json.^a from test_wide_map;
select json.^a, json.a.a1 from test_wide_map;
select json.a.a1, json.^a from test_wide_map;
select json from test_wide_map limit 3;
select json.b from test_wide_map limit 3;
select json.b, json.c from test_wide_map limit 3;
select json, json.b, json.c from test_wide_map limit 3;
select json.b, json.c, json from test_wide_map limit 3;
select json.^a from test_wide_map limit 3;
select json, json.^a from test_wide_map limit 3;
select json.^a, json.a.a1 from test_wide_map limit 3;
select json.a.a1, json.^a from test_wide_map limit 3;
select json from test_wide_map settings max_block_size=3;
select json.b from test_wide_map settings max_block_size=3;
select json.b, json.c from test_wide_map settings max_block_size=3;
select json, json.b, json.c from test_wide_map settings max_block_size=3;
select json.b, json.c, json from test_wide_map settings max_block_size=3;
select json.^a from test_wide_map settings max_block_size=3;
select json, json.^a from test_wide_map settings max_block_size=3;
select json.^a, json.a.a1 from test_wide_map settings max_block_size=3;
select json.a.a1, json.^a from test_wide_map settings max_block_size=3;
select json.data from test_wide_map_tuple;
select json.data, json.data.b from test_wide_map_tuple;
select json.data.b, json.data from test_wide_map_tuple;
select json.data, json.data.b, json.data.c from test_wide_map_tuple;
select json.data.b, json.data, json.data.c from test_wide_map_tuple;
select json.data.b, json.data.c, json.data from test_wide_map_tuple;
select json.data, json.data.^a from test_wide_map_tuple;
select json.data.^a, json.data from test_wide_map_tuple;
select json.data, json.data.^a, json.data.b from test_wide_map_tuple;
select json.data.b, json.data.^a, json.data from test_wide_map_tuple;
select json.data from test_wide_map_tuple limit 3;
select json.data, json.data.b from test_wide_map_tuple limit 3;
select json.data.b, json.data from test_wide_map_tuple limit 3;
select json.data, json.data.b, json.data.c from test_wide_map_tuple limit 3;
select json.data.b, json.data, json.data.c from test_wide_map_tuple limit 3;
select json.data.b, json.data.c, json.data from test_wide_map_tuple limit 3;
select json.data, json.data.^a from test_wide_map_tuple limit 3;
select json.data.^a, json.data from test_wide_map_tuple limit 3;
select json.data, json.data.^a, json.data.b from test_wide_map_tuple limit 3;
select json.data.b, json.data.^a, json.data from test_wide_map_tuple limit 3;
select json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.b from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.b, json.data.c from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data, json.data.c from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data.c, json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.^a from test_wide_map_tuple settings max_block_size=3;
select json.data.^a, json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.^a, json.data.b from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data.^a, json.data from test_wide_map_tuple settings max_block_size=3;
