set output_format_json_quote_64bit_integers=0;
create table source (json JSON(max_dynamic_paths=8)) engine=Memory;
create table test_compact_map (json JSON(max_dynamic_paths=8)) engine=MergeTree order by tuple() settings index_granularity=2, min_bytes_for_wide_part='200G', min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map', object_shared_data_serialization_version_for_zero_level_parts='map';
select json from test_compact_map;
select json.b from test_compact_map;
select json.b, json.c from test_compact_map;
select json, json.b, json.c from test_compact_map;
select json.b, json.c, json from test_compact_map;
select json.^a from test_compact_map;
select json, json.^a from test_compact_map;
select json.^a, json.a.a1 from test_compact_map;
select json.a.a1, json.^a from test_compact_map;
create table test_compact_map_tuple (json Tuple(data JSON(max_dynamic_paths=8))) engine=MergeTree order by tuple() settings index_granularity=2, min_bytes_for_wide_part='200G', min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map', object_shared_data_serialization_version_for_zero_level_parts='map';
select json.data from test_compact_map_tuple;
select json.data, json.data.b from test_compact_map_tuple;
select json.data.b, json.data from test_compact_map_tuple;
select json.data, json.data.b, json.data.c from test_compact_map_tuple;
select json.data.b, json.data, json.data.c from test_compact_map_tuple;
select json.data.b, json.data.c, json.data from test_compact_map_tuple;
select json.data, json.data.^a from test_compact_map_tuple;
select json.data.^a, json.data from test_compact_map_tuple;
select json.data, json.data.^a, json.data.b from test_compact_map_tuple;
select json.data.b, json.data.^a, json.data from test_compact_map_tuple;
create table test_wide_map (json JSON(max_dynamic_paths=8)) engine=MergeTree order by tuple() settings index_granularity=2, min_bytes_for_wide_part=1, min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map', object_shared_data_serialization_version_for_zero_level_parts='map';
select json from test_wide_map;
select json.b from test_wide_map;
select json.b, json.c from test_wide_map;
select json, json.b, json.c from test_wide_map;
select json.b, json.c, json from test_wide_map;
select json.^a from test_wide_map;
select json, json.^a from test_wide_map;
select json.^a, json.a.a1 from test_wide_map;
select json.a.a1, json.^a from test_wide_map;
select json from test_wide_map limit 3;
select json.b from test_wide_map limit 3;
select json.b, json.c from test_wide_map limit 3;
select json, json.b, json.c from test_wide_map limit 3;
select json.b, json.c, json from test_wide_map limit 3;
select json.^a from test_wide_map limit 3;
select json, json.^a from test_wide_map limit 3;
select json.^a, json.a.a1 from test_wide_map limit 3;
select json.a.a1, json.^a from test_wide_map limit 3;
select json from test_wide_map settings max_block_size=3;
select json.b from test_wide_map settings max_block_size=3;
select json.b, json.c from test_wide_map settings max_block_size=3;
select json, json.b, json.c from test_wide_map settings max_block_size=3;
select json.b, json.c, json from test_wide_map settings max_block_size=3;
select json.^a from test_wide_map settings max_block_size=3;
select json, json.^a from test_wide_map settings max_block_size=3;
select json.^a, json.a.a1 from test_wide_map settings max_block_size=3;
select json.a.a1, json.^a from test_wide_map settings max_block_size=3;
create table test_wide_map_tuple (json Tuple(data JSON(max_dynamic_paths=8))) engine=MergeTree order by tuple() settings index_granularity=2, min_bytes_for_wide_part=1, min_rows_for_wide_part=1, write_marks_for_substreams_in_compact_parts=1, object_serialization_version='v3', object_shared_data_serialization_version='map', object_shared_data_serialization_version_for_zero_level_parts='map';
select json.data from test_wide_map_tuple;
select json.data, json.data.b from test_wide_map_tuple;
select json.data.b, json.data from test_wide_map_tuple;
select json.data, json.data.b, json.data.c from test_wide_map_tuple;
select json.data.b, json.data, json.data.c from test_wide_map_tuple;
select json.data.b, json.data.c, json.data from test_wide_map_tuple;
select json.data, json.data.^a from test_wide_map_tuple;
select json.data.^a, json.data from test_wide_map_tuple;
select json.data, json.data.^a, json.data.b from test_wide_map_tuple;
select json.data.b, json.data.^a, json.data from test_wide_map_tuple;
select json.data from test_wide_map_tuple limit 3;
select json.data, json.data.b from test_wide_map_tuple limit 3;
select json.data.b, json.data from test_wide_map_tuple limit 3;
select json.data, json.data.b, json.data.c from test_wide_map_tuple limit 3;
select json.data.b, json.data, json.data.c from test_wide_map_tuple limit 3;
select json.data.b, json.data.c, json.data from test_wide_map_tuple limit 3;
select json.data, json.data.^a from test_wide_map_tuple limit 3;
select json.data.^a, json.data from test_wide_map_tuple limit 3;
select json.data, json.data.^a, json.data.b from test_wide_map_tuple limit 3;
select json.data.b, json.data.^a, json.data from test_wide_map_tuple limit 3;
select json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.b from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.b, json.data.c from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data, json.data.c from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data.c, json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.^a from test_wide_map_tuple settings max_block_size=3;
select json.data.^a, json.data from test_wide_map_tuple settings max_block_size=3;
select json.data, json.data.^a, json.data.b from test_wide_map_tuple settings max_block_size=3;
select json.data.b, json.data.^a, json.data from test_wide_map_tuple settings max_block_size=3;
