select json from test_compact_map format Null;
select json.b from test_compact_map format Null;
select json.b, json.c from test_compact_map format Null;
select json, json.b, json.c from test_compact_map format Null;
select json.b, json.c, json from test_compact_map format Null;
select json.^a from test_compact_map format Null;
select json, json.^a from test_compact_map format Null;
select json.^a, json.a.a1 from test_compact_map format Null;
select json.a.a1, json.^a from test_compact_map format Null;
select json.data from test_compact_map_tuple format Null;
select json.data, json.data.b from test_compact_map_tuple format Null;
select json.data.b, json.data from test_compact_map_tuple format Null;
select json.data, json.data.b, json.data.c from test_compact_map_tuple format Null;
select json.data.b, json.data, json.data.c from test_compact_map_tuple format Null;
select json.data.b, json.data.c, json.data from test_compact_map_tuple format Null;
select json.data, json.data.^a from test_compact_map_tuple format Null;
select json.data.^a, json.data from test_compact_map_tuple format Null;
select json.data, json.data.^a, json.data.b from test_compact_map_tuple format Null;
select json.data.b, json.data.^a, json.data from test_compact_map_tuple format Null;
