select json from test_compact_without_substreams_advanced format Null;
select json from test_compact_advanced format Null;
select json.b from test_compact_advanced format Null;
select json.b, json.c from test_compact_advanced format Null;
select json.arr[].arr1 from test_compact_advanced format Null;
select json.arr[].arr1, json.arr[].arr2 from test_compact_advanced format Null;
select json.arr[].arr2, json.arr[].arr1 from test_compact_advanced format Null;
select json.arr[].arr1, json.arr[].arr4 from test_compact_advanced format Null;
select json.arr[].arr4, json.arr[].arr1 from test_compact_advanced format Null;
select json.arr[].arr1, json.arr[].arr99 from test_compact_advanced format Null;
select json.arr, json.arr[].arr1 from test_compact_advanced format Null;
select json.arr[].arr1, json.arr from test_compact_advanced format Null;
select json, json.b, json.c from test_compact_advanced format Null;
select json.b, json.c, json from test_compact_advanced format Null;
select json, json.b, json.c, json.arr[].arr1 from test_compact_advanced format Null;
select json.b, json.c, json.arr[].arr1, json from test_compact_advanced format Null;
select json, json.b, json.c, json.arr, json.arr[].arr1 from test_compact_advanced format Null;
select json.b, json.c, json.arr[].arr1, json.arr, json from test_compact_advanced format Null;
select json.^a from test_compact_advanced format Null;
select json, json.^a from test_compact_advanced format Null;
select json.^a, json.a.a1 from test_compact_advanced format Null;
select json.a.a1, json.^a from test_compact_advanced format Null;
select json.^a, json.a.a1, json.a.arr[].arr1 from test_compact_advanced format Null;
select json.a.a1, json.a.arr[].arr1, json.^a from test_compact_advanced format Null;
select json, json.a.a1, json.a.arr[].arr1, json.^a from test_compact_advanced format Null;
select json.a.a1, json.a.arr[].arr1, json.^a, json from test_compact_advanced format Null;
select json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_compact_advanced format Null;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a from test_compact_advanced format Null;
select json, json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_compact_advanced format Null;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a, json from test_compact_advanced format Null;
select json.arr[].arr1, json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_compact_advanced format Null;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a, json.arr[].arr1 from test_compact_advanced format Null;
select json, json.arr[].arr1, json.^a, json.a.a1, json.a.arr[].arr1, json.b, json.arr from test_compact_advanced format Null;
select json.a.a1, json.a.arr[].arr1, json.b, json.arr, json.^a, json.arr[].arr1, json from test_compact_advanced format Null;
