SELECT '---';
SELECT count() FROM test_join_remote_l x JOIN cluster(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x JOIN clusterAllReplicas(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x JOIN remote(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x JOIN remoteSecure(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x RIGHT JOIN cluster(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x RIGHT JOIN clusterAllReplicas(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x RIGHT JOIN remote(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM test_join_remote_l x RIGHT JOIN remoteSecure(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_r) y ON TRUE;
SELECT count() FROM cluster(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM clusterAllReplicas(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM remote(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM remoteSecure(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM cluster(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x RIGHT JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM clusterAllReplicas(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x RIGHT JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM remote(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x RIGHT JOIN test_join_remote_r y ON TRUE;
SELECT count() FROM remoteSecure(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), test_join_remote_l) x RIGHT JOIN test_join_remote_r y ON TRUE;
