SET query_plan_use_new_logical_join_step = 0;
SET enable_analyzer = 1;
CREATE TABLE t1 (x Int8) ENGINE = Memory;
CREATE TABLE t2 (x UInt8) ENGINE = Memory;
CREATE TABLE t3 (x UInt16) ENGINE = Memory;
CREATE TABLE t4 (x UInt32) ENGINE = Memory;
SELECT coalesce(t1.x, t2.x, t3.x, t4.x) AS x
FROM t1
FULL OUTER JOIN t2 USING (x)
FULL OUTER JOIN t3 USING (x)
FULL OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
FULL OUTER JOIN t2 USING (x)
FULL OUTER JOIN t3 USING (x)
FULL OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
RIGHT OUTER JOIN t2 USING (x)
RIGHT OUTER JOIN t3 USING (x)
RIGHT OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
LEFT OUTER JOIN t2 USING (x)
LEFT OUTER JOIN t3 USING (x)
LEFT OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
RIGHT OUTER JOIN t2 USING (x)
FULL OUTER JOIN t3 USING (x)
INNER JOIN t4 USING (x)
;
