SELECT coalesce(t1.x, t2.x, t3.x, t4.x) AS x
FROM t1
FULL OUTER JOIN t2 USING (x)
FULL OUTER JOIN t3 USING (x)
FULL OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
FULL OUTER JOIN t2 USING (x)
FULL OUTER JOIN t3 USING (x)
FULL OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
RIGHT OUTER JOIN t2 USING (x)
RIGHT OUTER JOIN t3 USING (x)
RIGHT OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
LEFT OUTER JOIN t2 USING (x)
LEFT OUTER JOIN t3 USING (x)
LEFT OUTER JOIN t4 USING (x)
;
SELECT 1 as x
FROM t1
RIGHT OUTER JOIN t2 USING (x)
FULL OUTER JOIN t3 USING (x)
INNER JOIN t4 USING (x)
;
