SELECT count() > 0 FROM (
  WITH RECURSIVE q AS (
    SELECT 1 FROM t0 UNION ALL
      (WITH RECURSIVE x AS
        (SELECT 1 FROM t0 UNION ALL
          (SELECT 1 FROM q WHERE FALSE UNION ALL
           SELECT 1 FROM x WHERE FALSE))
         SELECT 1 FROM x))
    SELECT 1 FROM q
); -- { serverError TOO_DEEP_RECURSION }
