SELECT lag(number) OVER (ORDER BY number ASC)
FROM remote('127.0.0.1', numbers(5));

SELECT lead(number) OVER (ORDER BY number ASC)
FROM remote('127.0.0.1', numbers(5));

SELECT lag(number) OVER (ORDER BY number ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED PRECEDING)
FROM numbers(5);

SELECT lead(number) OVER (ORDER BY number ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED PRECEDING)
FROM numbers(5);