SELECT toString(v) FROM vf_null_only;
SELECT toTypeName(toString(v)) FROM vf_null_only LIMIT 1;
SELECT toString(v) FROM vf_one_variant_no_nulls;
SELECT toTypeName(toString(v)) FROM vf_one_variant_no_nulls LIMIT 1;
SELECT toString(v) FROM vf_one_variant_with_nulls;
SELECT toTypeName(toString(v)) FROM vf_one_variant_with_nulls LIMIT 1;
SELECT toString(v) FROM vf_multi_variant;
SELECT toTypeName(toString(v)) FROM vf_multi_variant LIMIT 1;
SELECT toString(v) FROM vf_multi_variant WHERE 0;
SELECT arrayElement(v, 1) FROM vf_array_one_variant_no_nulls;
SELECT toTypeName(arrayElement(v, 1)) FROM vf_array_one_variant_no_nulls LIMIT 1;
SELECT arrayElement(v, 1) FROM vf_array_one_variant_with_nulls;
SELECT toTypeName(arrayElement(v, 1)) FROM vf_array_one_variant_with_nulls LIMIT 1;
SELECT arrayElement(v, 1) FROM vf_array_multi_variant;
SELECT toTypeName(arrayElement(v, 1)) FROM vf_array_multi_variant LIMIT 1;
SELECT toString(v), (v = CAST(42 AS UInt64)) AS is_42 FROM vf_equals;
SELECT toString(v), (CAST(42 AS UInt64) = v) AS is_42 FROM vf_equals;
SELECT v + x FROM vf_variant_nullable;
SELECT toTypeName(v + x) FROM vf_variant_nullable LIMIT 1;
SELECT v1 + v2 FROM vf_two_variants_all_nulls;
SELECT toTypeName(v1 + v2) FROM vf_two_variants_all_nulls LIMIT 1;
SELECT v1 + v2 FROM vf_two_variants_single_no_nulls;
SELECT toTypeName(v1 + v2) FROM vf_two_variants_single_no_nulls LIMIT 1;
SELECT v1 + v2 FROM vf_two_variants_single_with_nulls;
SELECT toTypeName(v1 + v2) FROM vf_two_variants_single_with_nulls LIMIT 1;
SELECT v1 + v2 FROM vf_two_variants_multiple;
SELECT toTypeName(v1 + v2) FROM vf_two_variants_multiple LIMIT 1;
