#!/usr/bin/env tsx

/**
 * Shows the `EXPLAIN AST json = 1` output produced by explainJSON() for one or
 * more vendored reference cases (tests/clickhouse-reference-ast-json/cases),
 * the expected JSON generated by the reference ClickHouse build, and the diff
 * between them.
 *
 * Both sides are re-serialized with sorted object keys so key order never
 * causes spurious diffs (the comparison is structural, like the test suite).
 *
 * Run via: npm run diff:ast-json -- <reference> [options]   (see --help)
 */

import { explainJSON, parse } from '../src/index.js';
import { parseCli, run } from './diff-lib.js';

const CASES_DIR = new URL('../tests/clickhouse-reference-ast-json/cases', import.meta.url)
  .pathname;

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value !== null && typeof value === 'object') {
    const result: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      result[key] = sortKeys((value as Record<string, unknown>)[key]);
    }
    return result;
  }
  return value;
}

function canonicalize(json: unknown): string {
  return JSON.stringify(sortKeys(json), null, 2);
}

const opts = parseCli(
  process.argv,
  'diff:ast-json',
  'explainJSON() output vs. vendored EXPLAIN AST json = 1 output',
);

run(
  opts,
  '.json',
  (sql) => {
    const statements = parse(sql);
    if (statements.length !== 1) {
      throw new Error(`expected exactly one statement, got ${statements.length}`);
    }
    return canonicalize(explainJSON(statements[0]).ast);
  },
  {
    dir: CASES_DIR,
    expectedPathFor: (sqlPath) => sqlPath.replace(/\.sql$/, '.json'),
    normalizeExpected: (expected) => {
      const parsed = JSON.parse(expected) as Record<string, unknown>;
      // Fixtures may be the bare AST node or the {version, ast} document.
      return canonicalize('ast' in parsed ? parsed.ast : parsed);
    },
  },
);

